---
 - name: VPC+SUBNETS provision
   local_action:
     module: ec2_vpc
     region: '{{aws_region}}'
     cidr_block: '{{aws_vpc}}'
     resource_tags: '{"Name":"{{aws_prefix}}_vpc"}'
     subnets:
       - cidr: '{{aws_subnet}}'
        #  az: "{{ aws_az0 }}"
         resource_tags: '{"Name":"{{aws_prefix}}_net_1"}'
      #  - cidr: 10.0.2.64/26
      #    az: "{{ aws_az1 }}"
      #    resource_tags: '{"Name":"{{ aws_prefix }}_net_1b"}'
      #  - cidr: 10.0.2.128/26
      #    az: "{{ aws_az2 }}"
      #    resource_tags: '{"Name":"{{ aws_prefix }}_net_1c"}'
     internet_gateway: yes
     route_tables:
       - subnets:
           - '{{aws_subnet}}'
         routes:
           - dest: 0.0.0.0/0
             gw: igw
   register: vpc
 - name: write vpc id to {{aws_vars_file}} file
  #  sudo: yes
   become: true
   local_action: shell echo "{{aws_prefix}}"_vpc":" "{{vpc.vpc_id}}"
                   > '{{aws_vars_file}}'
 - name: write subnets id to {{aws_vars_file}} file
   become: true
   local_action: shell echo "{{item.resource_tags.Name}}"":" "{{item.id}}"
                   >> '{{aws_vars_file}}'
   with_items: '{{vpc.subnets}}'

 - name: SG provision
   local_action:
     module: ec2_group
     region: '{{aws_region}}'
     vpc_id: '{{vpc.vpc_id}}'
     # your security group name
     name: '{{aws_prefix}}_sg'
     description: security group for HDP cluster
     rules:
       # Allow to ping hosts
       - proto: icmp
         # from_port: 8 # icmp type, -1 = any type
         from_port: -1
         to_port:  -1
         cidr_ip: 0.0.0.0/0
        #  group_id: '{{name}}'
       # Allow ssh access from anywhere
       - proto: tcp
         from_port: 22
         to_port: 22
         cidr_ip: 0.0.0.0/0
       # Allow some access for test from anywhere
       # - proto: tcp
       #   from_port: 2222
       #   to_port: 2222
       #   cidr_ip: 0.0.0.0/0
       # Allow http access from anywhere
       - proto: tcp
         from_port: 80
         to_port: 80
         cidr_ip: 0.0.0.0/0
     rules_egress:
       - proto: all
         cidr_ip: 0.0.0.0/0
   register: sg
 # - name: write vpc id to {{aws_vars_file}} file
 #   become: true
 #   local_action: shell echo "{{aws_prefix}}"_vpc":" "{{vpc.vpc_id}}"
 #                   > '{{aws_vars_file}}'
 # - name: write subnets id to {{aws_vars_file}} file
 #   become: true
 #   local_action: shell echo "{{item.resource_tags.Name}}"":" "{{item.id}}"
 #                   >> '{{aws_vars_file}}'
 #   with_items: '{{vpc.subnets}}'

 - include_vars: "{{aws_vars_file}}"

 - name: Data Nodes Provision

   local_action:
     module: ec2
     key_name: '{{ec2_keypair}}'
     group_id: '{{sg.group_id}}'
     #group: '{{aws_prefix}}_sg'
     instance_type: '{{ec2_dn_instance_type}}'
     image: '{{ec2_image}}'
     #vpc_subnet_id: '{{ec2_subnet_ids|random}}'
     vpc_subnet_id: '{{hdp24_net_1}}'
     region: '{{aws_region}}'
     instance_tags: '{"Name":"{{ec2_tag_dn_Name}}-{{item}}","Type":"{{ec2_tag_Type}}","Environment":"{{ec2_tag_Environment}}"}'
     # assign_public_ip only available with vpc_subnet_id
     assign_public_ip: yes
     wait: yes
     volumes:
     - device_name: /dev/sda
      #  volume_type: gp2
       volume_size: '{{ec2_root_disk_size}}'
       delete_on_termination: true
     - device_name: /dev/sdb
      #  volume_type: gp2
       volume_size: '{{ec2_swap_size}}'
       delete_on_termination: true
     - device_name: /dev/sdc
      #  volume_type: gp2
       volume_size: '{{ec2_data_disk_size}}'
       delete_on_termination: true
   with_sequence: count='{{ec2_dn_number}}'
  #  register: ec2

- name: Name Nodes Provision

  local_action:
    module: ec2
    key_name: '{{ec2_keypair}}'
    group_id: '{{sg.group_id}}'
    #group: '{{aws_prefix}}_sg'
    instance_type: '{{ec2_nn_instance_type}}'
    image: '{{ec2_image}}'
    #vpc_subnet_id: '{{ec2_subnet_ids|random}}'
    vpc_subnet_id: '{{hdp24_net_1}}'
    region: '{{aws_region}}'
    instance_tags: '{"Name":"{{ec2_tag_nn_Name}}-{{item}}","Type":"{{ec2_tag_Type}}","Environment":"{{ec2_tag_Environment}}"}'
    # assign_public_ip only available with vpc_subnet_id
    assign_public_ip: yes
    wait: yes
    volumes:
    - device_name: /dev/sda
      # volume_type: gp2
      volume_size: '{{ec2_root_disk_size}}'
      delete_on_termination: true
    - device_name: /dev/sdb
      # volume_type: gp2
      volume_size: '{{ec2_swap_size}}'
      delete_on_termination: true
  with_sequence: count='{{ec2_nn_number}}'
 # register: ec2

- name: Provision Secondary Name Nodes

  local_action:
    module: ec2
    key_name: '{{ec2_keypair}}'
    group_id: '{{sg.group_id}}'
    #group: '{{aws_prefix}}_sg'
    instance_type: '{{ec2_sn_instance_type}}'
    image: '{{ec2_image}}'
    #vpc_subnet_id: '{{ec2_subnet_ids|random}}'
    vpc_subnet_id: '{{hdp24_net_1}}'
    region: '{{aws_region}}'
    instance_tags: '{"Name":"{{ec2_tag_sn_Name}}-{{item}}","Type":"{{ec2_tag_Type}}","Environment":"{{ec2_tag_Environment}}"}'
    # assign_public_ip only available with vpc_subnet_id
    assign_public_ip: yes
    wait: yes
    volumes:
    - device_name: /dev/sda
      # volume_type: gp2
      volume_size: '{{ec2_root_disk_size}}'
      delete_on_termination: true
    - device_name: /dev/sdb
      # volume_type: gp2
      volume_size: '{{ec2_swap_size}}'
      delete_on_termination: true
  with_sequence: count='{{ec2_sn_number}}'

 # - debug: var=item
 #   with_items: ec2.instances

 - debug:
     msg: '{{ item }}'
   with_file:
     - '{{aws_vars_file}}'
 # - name: Wait for the instances to boot by checking the ssh port
 #   wait_for: host={{item.public_ip}} port=22 delay=60 timeout=320 state=started
 #   with_items: ec2.instances
