---  
- hosts: localhost  
  gather_facts: no    
  vars:  
    region: eu-west-1 
    # prefix for naming  
    prefix: hdp1
    # availability zones
    az0: "{{ region }}a"
    az1: "{{ region }}b"
    az2: "{{ region }}c"
  tasks:  
    - name: create vpc with multi-az subnets   
      local_action:  
        module: ec2_vpc     
        region: "{{ region }}"
        cidr_block: 10.0.2.0/24
        resource_tags: '{"Name":"{{ prefix }}_vpc"}'
        subnets:
          - cidr: 10.0.2.0/26
            az: "{{ az0 }}"
            resource_tags: '{"Name":"{{ prefix }}_net_1a"}'
          - cidr: 10.0.2.64/26
            az: "{{ az1 }}"
            resource_tags: '{"Name":"{{ prefix }}_net_1b"}'
          - cidr: 10.0.2.128/26
            az: "{{ az2 }}"
            resource_tags: '{"Name":"{{ prefix }}_net_1c"}'
        internet_gateway: yes
        route_tables:
          - subnets:
              - 10.0.2.0/26
              - 10.0.2.64/26
              - 10.0.2.128/26
            routes:
              - dest: 0.0.0.0/0
                gw: igw
      register: vpc
    - name: write vpc id to {{ prefix }}_vpc_info file
      sudo: yes
      local_action: shell echo "{{ prefix }}"_vpc":" "{{ vpc.vpc_id }}" 
                      > "{{ prefix }}"_vpc_info
    - name: write subnets id to {{ prefix }}_vpc_info file
      sudo: yes
      local_action: shell echo "{{ item.resource_tags.Name }}"":" "{{ item.id }}" 
                      >> "{{ prefix }}"_vpc_info
      with_items: vpc.subnets
